# {
#   "name": "Catppuccin Mocha",
#   "colorscheme": "dark",
#   "colors": {
#     "text": "#cdd6f4",
#     "subtext2": "#bec6e0",
#     "subtext1": "#bac2de",
#     "subtext0": "#a6adc8",
#     "overlay2": "#989db5",
#     "overlay1": "#9399b2",
#     "overlay0": "#7f849c",
#     "surface2": "#6c7086",
#     "surface1": "#585b70",
#     "surface0": "#45475a",
#     "base": "#313244",
#     "crust": "#1e1e2e",
#     "mantle": "#181825"
#   }
# }

[info]
name = "Catppuccin Mocha"
author = "Rhyolite Team"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#cdd6f4"
subtext2 = "#bec6e0"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#989db5"
overlay1 = "#9399b2"
overlay0 = "#7f849c"
surface2 = "#6c7086"
surface1 = "#585b70"
surface0 = "#45475a"
base = "#313244"
crust = "#1e1e2e"
mantle = "#181825"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
