[info]
name = "Catppuccin Latte"
author = "RedddFoxxyy (aka Suyog Tandel) (https://github.com/RedddFoxxyy)"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#4c4f69"
subtext2 = "#5a5d75"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#75788c"
overlay1 = "#7c7f93"
overlay0 = "#8c8fa1"
surface2 = "#9ca0b0"
surface1 = "#acb0be"
surface0 = "#bcc0cc"
base = "#ccd0da"
crust = "#eff1f5"
mantle = "#e6e9ef"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
