# {
#   "name": "Catppuccin Macchiato",
#   "colorscheme": "dark",
#   "colors": {
#     "text": "#cad3f5",
#     "subtext2": "#bec5e0",
#     "subtext1": "#b8c0e0",
#     "subtext0": "#a5adcb",
#     "overlay2": "#939ab7",
#     "overlay1": "#8087a2",
#     "overlay0": "#6e738d",
#     "surface2": "#5e6277",
#     "surface1": "#5b6078",
#     "surface0": "#494d64",
#     "base": "#363a4f",
#     "crust": "#24273a",
#     "mantle": "#1e2030"
#   }
# }

[info]
name = "Catppuccin Macchiato"
author = "RedddFoxxyy (aka Suyog Tandel) (https://github.com/RedddFoxxyy)"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#cad3f5"
subtext2 = "#bec5e0"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5e6277"
surface1 = "#5b6078"
surface0 = "#494d64"
base = "#363a4f"
crust = "#24273a"
mantle = "#1e2030"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
