[info]
name = "Crimson Nocturne"
author = "RedddFoxxyy (aka Suyog Tandel) (https://github.com/RedddFoxxyy)"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#FADCD5"
subtext2 = "#FADCD5"
subtext1 = "#765D67"
subtext0 = "#6D3C52"
overlay2 = "#765D67"
overlay1 = "#6D3C52"
overlay0 = "#4B2138"
surface2 = "#765D67"
surface1 = "#6D3C52"
surface0 = "#6D3C52"
base = "#4B2138"
crust = "#1B0C1A"
mantle = "#2D222F"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
