[info]
name = "Default"
author = "Rhyolite Team"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#ffffff"
subtext2 = "#f1f2f3"
subtext1 = "#d8dbde"
subtext0 = "#c2c6cb"
overlay2 = "#acb2b8"
overlay1 = "#969da5"
overlay0 = "#808992"
surface2 = "#6c757d" # Applied to close tab icon hover background.
surface1 = "#596167" # Applied to tab buttons when hovered.
surface0 = "#464c51" # Applied to tab buttons.
base = "#33373b" # Applied to TitleBar/TabsBar.
crust = "#202325"
mantle = "#0d0e0f"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
