[info]
name = "Green Screen"
author = "Rhyolite Team"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#e5ffe6"
subtext2 = "#def8df"
subtext1 = "#d4eed5"
subtext0 = "#c4ddc5"
overlay2 = "#c4ddce"
overlay1 = "#ceddc4"
overlay0 = "#a1b9ab"
surface2 = "#a1b9a1"
surface1 = "#819982"
surface0 = "#5a705b"
base = "#475c48"
crust = "#293e2a"
mantle = "#081d08"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
