# {
#   "name": "Rose Pine Main",
#   "colorscheme": "light",
#   "colors": {
#     "text": "#c4a7e7",
#     "subtext2": "#e0def4",
#     "subtext1": "#d8dbde",
#     "subtext0": "#c2c6cb",
#     "surface0": "#403d52",
#     "surface1": "#524f67",
#     "surface2": "#6e6a86",
#     "overlay0": "#26233a",
#     "overlay1": "#6e6a86",
#     "overlay2": "#26233a",
#     "base": "#26233a",
#     "crust": "#191724",
#     "mantle": "#c4a7e7"
#   }
# }

[info]
name = "Rose Pine Main"
author = "Shravya Kudlu"
themetype = "Basic"
colorscheme = "Dark"

[colors]
text = "#c4a7e7"
subtext2 = "#e0def4"
subtext1 = "#d8dbde"
subtext0 = "#c2c6cb"
overlay2 = "#26233a"
overlay1 = "#6e6a86"
overlay0 = "#26233a"
surface2 = "#6e6a86"
surface1 = "#524f67"
surface0 = "#403d52"
base = "#26233a"
crust = "#191724"
mantle = "#c4a7e7"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
