# {
#   "name": "Rose Pine Dawn",
#   "colorscheme": "light",
#   "colors": {
#     "text": "#ea9d34",
#     "subtext2": "#e0b94b",
#     "subtext1": "#d59a42",
#     "subtext0": "#c9944f",
#     "overlay2": "#d29b7e",
#     "overlay1": "#d29b7e",
#     "overlay0": "#b07a5f",
#     "surface2": "#f9d39f",
#     "surface1": "#eec5c4",
#     "surface0": "#fffaf3",
#     "base": "#f2e9e1",
#     "crust": "#faf4ed",
#     "mantle": "#e0c7b6"
#   }
# }

[info]
name = "Rose Pine Dawn"
author = "Rhyolite Team"
themetype = "Basic"
colorscheme = "Light"

[colors]
text = "#ea9d34"
subtext2 = "#e0b94b"
subtext1 = "#d59a42"
subtext0 = "#c9944f"
overlay2 = "#d29b7e"
overlay1 = "#d29b7e"
overlay0 = "#b07a5f"
surface2 = "#f9d39f"
surface1 = "#eec5c4"
surface0 = "#fffaf3"
base = "#f2e9e1"
crust = "#faf4ed"
mantle = "#e0c7b6"
accent = "#ff4081"
highlight = "#ffa726"
border = "#424242"
