name: Rust CI Pipeline

on:
  push:
    branches:
      - master
      - release
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

  pull_request:
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 libgl1 libx11-6 libxcb1 libxau6 libxdmcp6 \
            libfontconfig1 libfreetype6 libpng16-16 libexpat1 \
            zlib1g libbrotli1 libstdc++6 libgcc-s1 \
            libfreetype6-dev \
            libfontconfig1-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libwayland-egl1-mesa \
            libgles2-mesa-dev \
            libwayland-egl-backend-dev \
            libwayland-dev

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build project
        run: cargo build --verbose --all-features