name: Rust CI Pipeline

on:
    push:
        branches:
            - master
        paths:
            - "src-tauri/src/**"
    pull_request:
        branches:
            - master
        paths:
            - "src-tauri/src/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: install dependencies (ubuntu only)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
              # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
              # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

            - name: install frontend dependencies
              run: npm install # change this to npm, pnpm or bun depending on which one you use.

            - name: Build project
              run: cargo build --verbose
              working-directory: src-tauri

            - name: Run tests
              run: cargo test
              working-directory: src-tauri

            - name: Run linter
              run: cargo clippy -- -D warnings
              working-directory: src-tauri

            - name: Generate documentation
              run: cargo doc --no-deps --document-private-items
              working-directory: src-tauri
